# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='isAdmin',
            new_name='is_admin',
        ),
    ]
