# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantry.FoodItem')),
            ],
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantry.FoodItem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('item',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('source', models.URLField(blank=True, max_length=500)),
                ('courses', models.ManyToManyField(blank=True, to='pantry.Course')),
                ('cuisines', models.ManyToManyField(blank=True, to='pantry.Cuisine')),
                ('ingredients', models.ManyToManyField(blank=True, to='pantry.Ingredient')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pantryitem',
            unique_together=set([('item', 'owner')]),
        ),
    ]
