# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.URLField()),
                ('cuisines', models.CharField(max_length=500)),
                ('courses', models.CharField(max_length=500)),
                ('ingredients', models.CharField(max_length=20000)),
            ],
        ),
    ]
